In [1]:
import cv2
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [5]:
src_dir = '../../data/render'
src_shading_dir = src_dir + '/shade'
src_shading = src_shading_dir + '/{:05d}.png'.format(0)

shading_1ch = cv2.imread(src_shading, 0)
shading_3ch = cv2.imread(src_shading, 1)

In [6]:
shading_1ch.shape

(1200, 1600)

In [7]:
shading_3ch.shape

(1200, 1600, 3)

In [8]:
shading_2ch = np.dstack([shading_1ch, shading_1ch])
shading_2ch.shape

(1200, 1600, 2)

In [9]:
shift_max = 0.1
rotate_max = 45
zoom_range=[0.9, 1.1]

datagen_args = dict(
    rotation_range=rotate_max,
    width_shift_range=shift_max,
    height_shift_range=shift_max,
    shear_range=0,
    zoom_range=zoom_range,
    fill_mode='constant',
    cval=0
)

In [24]:
# 3ch
x = shading_3ch
x = x.reshape((1,) + x.shape)
datagen = ImageDataGenerator(**datagen_args)
datagen.fit(x, augment=True, seed=1)
generator = datagen.flow(x, batch_size=1, seed=1)

In [25]:
num = 8
imgs = []
for d in generator:
    imgs.append(d[0])
    if (len(imgs) % num) == 0:
        break

In [26]:
for i in range(num):
    cv2.imwrite('check_aug/aug_3ch-{:02d}.png'.format(i), imgs[i])

In [18]:
shading_1ch = shading_1ch.reshape(shading_1ch.shape + (1,))

# 1ch
x = shading_1ch
x = x.reshape((1,) + x.shape)
datagen = ImageDataGenerator(**datagen_args)
datagen.fit(x, augment=True, seed=1)
generator = datagen.flow(x, batch_size=1, seed=1)

In [19]:
num = 8
imgs = []
for d in generator:
    imgs.append(d[0])
    if (len(imgs) % num) == 0:
        break

In [20]:
for i in range(num):
    cv2.imwrite('check_aug/aug_1ch-{:02d}.png'.format(i), imgs[i])

In [27]:
# 2ch
x = shading_2ch
x = x.reshape((1,) + x.shape)
datagen = ImageDataGenerator(**datagen_args)
datagen.fit(x, augment=True, seed=1)
generator = datagen.flow(x, batch_size=1, seed=1)

In [28]:
num = 8
imgs = []
for d in generator:
    imgs.append(d[0])
    if (len(imgs) % num) == 0:
        break

In [30]:
for i in range(num):
    img = imgs[i]
    cv2.imwrite('check_aug/aug_2ch-0-{:02d}.png'.format(i), img[:, :, 0])

In [31]:
for i in range(num):
    img = imgs[i]
    cv2.imwrite('check_aug/aug_2ch-1-{:02d}.png'.format(i), img[:, :, 1])

In [33]:
# Mask
mask = np.zeros((10, 10))
mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
mask[3:7, 3:7] = 1
mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.sum(mask)

16.0

In [36]:
mask = mask.reshape(mask.shape + (1,))
mask

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]],

      

In [37]:
x = mask
x = x.reshape((1,) + x.shape)
datagen = ImageDataGenerator(**datagen_args)
datagen.fit(x, augment=True, seed=1)
generator = datagen.flow(x, batch_size=1, seed=1)

In [38]:
num = 8
imgs = []
for d in generator:
    imgs.append(d[0])
    if (len(imgs) % num) == 0:
        break

In [42]:
img = imgs[0]
img = img[:, :, 0]
img

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.10049278, 0.29266465,
        0.413455  , 0.5342454 , 0.4778095 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.4598531 , 1.        ,
        1.        , 1.        , 0.85427487, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.3350186 , 1.        ,
        1.        , 1.        , 0.97910935, 0.05764133, 0.        ],
       [0.        , 0.        , 0.        , 0.21018408, 1.        ,
        1.        , 1.        , 1.        , 0.18247584, 0.        ],
       [0.        , 0.        , 0.        , 0.08534958, 0.8980577 ,
        0.77726734, 0.656477  , 0.5356866 , 0.1275019 , 0.        ],
       [0.        , 0.        , 0.       

In [43]:
np.sum(img)

17.977564

In [44]:
img = imgs[1]
img = img[:, :, 0]
img

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.06202401, 0.09145721, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.3108797 , 0.84656173, 0.9453329 ,
        1.        , 0.6678522 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.31665963, 1.        , 1.        ,
        1.        , 0.76692355, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.21758828, 1.        , 1.        ,
        1.        , 0.86599493, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.1185169

In [45]:
np.sum(img)

16.473867

In [46]:
mask = np.zeros((120, 120))
mask[30:90, 30:90] = 1
np.sum(mask)

3600.0

In [47]:
mask = mask.reshape(mask.shape + (1,))

x = mask
x = x.reshape((1,) + x.shape)
datagen = ImageDataGenerator(**datagen_args)
datagen.fit(x, augment=True, seed=1)
generator = datagen.flow(x, batch_size=1, seed=1)

num = 8
imgs = []
for d in generator:
    imgs.append(d[0])
    if (len(imgs) % num) == 0:
        break

In [48]:
img = imgs[0]
img = img[:, :, 0]
np.sum(img)

4033.1074

In [49]:
img = imgs[1]
img = img[:, :, 0]
np.sum(img)

3706.169

In [50]:
img = imgs[2]
img = img[:, :, 0]
np.sum(img)

3330.54

In [51]:
mask = np.zeros((120, 120))
mask[60, :] = 1
mask[:, 60] = 1
np.sum(mask)

239.0

In [52]:
mask = mask.reshape(mask.shape + (1,))

x = mask
x = x.reshape((1,) + x.shape)
datagen = ImageDataGenerator(**datagen_args)
datagen.fit(x, augment=True, seed=1)
generator = datagen.flow(x, batch_size=1, seed=1)

num = 8
imgs = []
for d in generator:
    imgs.append(d[0])
    if (len(imgs) % num) == 0:
        break

In [53]:
img = imgs[0]
img = img[:, :, 0]
np.sum(img)

241.36191

In [54]:
img = imgs[1]
img = img[:, :, 0]
np.sum(img)

230.41559

In [55]:
img = imgs[2]
img = img[:, :, 0]
np.sum(img)

215.1893