In [1]:
import depth_tools
import cv2
import numpy as np

In [52]:
src_dir = '../../data/render'

src_frame_dir = src_dir + '/proj'
src_gt_dir = src_dir + '/gt'
src_shading_dir = src_dir + '/shade'
src_rec_dir = src_dir + '/rec'

data_idx = 1

src_bgra = src_frame_dir + '/{:05d}.png'.format(data_idx)
src_depth_gt = src_gt_dir + '/{:05d}.bmp'.format(data_idx)
src_shading = src_shading_dir + '/{:05d}.png'.format(data_idx)
src_depth_gap = src_rec_dir + '/{:05d}.bmp'.format(data_idx)

In [53]:
depth_img_gap = cv2.imread(src_depth_gap, -1)
depth_gap = depth_tools.unpack_bmp_bgra_to_float(depth_img_gap)

depth_img_gt = cv2.imread(src_depth_gt, -1)
depth_gt = depth_tools.unpack_bmp_bgra_to_float(depth_img_gt)

In [54]:
depth_thre = 0.02
difference_threshold = 0.1

In [55]:
depth_gap[600:610, 700:710]

array([[0.9699415 , 0.96991825, 0.96989584, 0.96987534, 0.96985781,
        0.96984422, 0.96983635, 0.96983457, 0.96984065, 0.96985531],
       [0.97005808, 0.97003436, 0.97001135, 0.96999002, 0.96997142,
        0.96995664, 0.96994722, 0.96994388, 0.96994793, 0.96996057],
       [0.97017384, 0.97014999, 0.97012663, 0.97010481, 0.97008538,
        0.97006965, 0.97005904, 0.97005427, 0.97005665, 0.97006738],
       [0.97028828, 0.97026455, 0.97024107, 0.97021902, 0.97019911,
        0.97018266, 0.97017109, 0.97016525, 0.97016633, 0.97017539],
       [0.97040093, 0.97037745, 0.97035432, 0.97033215, 0.97031212,
        0.97029531, 0.97028315, 0.97027636, 0.97027636, 0.97028399],
       [0.9705112 , 0.97048843, 0.97046566, 0.97044384, 0.97042394,
        0.97040701, 0.97039449, 0.9703871 , 0.97038627, 0.9703927 ],
       [0.97061896, 0.97059691, 0.97057486, 0.97055352, 0.97053397,
        0.97051728, 0.97050464, 0.97049701, 0.97049546, 0.97050107],
       [0.97072351, 0.97070253, 0.9706813

In [56]:
depth_gt[600:610, 700:710]

array([[0.96755743, 0.96769691, 0.96806943, 0.96864688, 0.96937728,
        0.97019351, 0.97103667, 0.97186422, 0.97263861, 0.9733094 ],
       [0.96800017, 0.96810782, 0.96844828, 0.96899128, 0.9696852 ,
        0.97046578, 0.97127783, 0.97207952, 0.97283435, 0.9734937 ],
       [0.96805465, 0.96813858, 0.96844923, 0.96895325, 0.96960199,
        0.97033978, 0.97111845, 0.97189462, 0.97262681, 0.97326756],
       [0.9677062 , 0.96778274, 0.96808338, 0.96857095, 0.96919739,
        0.96991289, 0.97067618, 0.97144282, 0.97216582, 0.97279489],
       [0.96717918, 0.96726632, 0.96758258, 0.96808684, 0.96872902,
        0.96945846, 0.97023475, 0.97101283, 0.97174478, 0.97237599],
       [0.96680081, 0.96691275, 0.9672612 , 0.96780443, 0.96849203,
        0.96926773, 0.97008276, 0.97088993, 0.97164285, 0.97228456],
       [0.96681046, 0.96694994, 0.96732891, 0.96791065, 0.96864951,
        0.96948266, 0.97034645, 0.97118568, 0.97195685, 0.9726063 ],
       [0.96723187, 0.96738923, 0.9677819

In [57]:
difference = depth_gt - depth_gap
difference[600:610, 700:710]

array([[-2.38406658e-03, -2.22134590e-03, -1.82640553e-03,
        -1.22845173e-03, -4.80532646e-04,  3.49283218e-04,
         1.20031834e-03,  2.02965736e-03,  2.79796124e-03,
         3.45408916e-03],
       [-2.05790997e-03, -1.92654133e-03, -1.56307220e-03,
        -9.98735428e-04, -2.86221504e-04,  5.09142876e-04,
         1.33061409e-03,  2.13563442e-03,  2.88641453e-03,
         3.53312492e-03],
       [-2.11918354e-03, -2.01141834e-03, -1.67739391e-03,
        -1.15156174e-03, -4.83393669e-04,  2.70128250e-04,
         1.05941296e-03,  1.84035301e-03,  2.57015228e-03,
         3.20017338e-03],
       [-2.58207321e-03, -2.48181820e-03, -2.15768814e-03,
        -1.64806843e-03, -1.00171566e-03, -2.69770622e-04,
         5.05089760e-04,  1.27756596e-03,  1.99949741e-03,
         2.61950493e-03],
       [-3.22175026e-03, -3.11112404e-03, -2.77173519e-03,
        -2.24530697e-03, -1.58309937e-03, -8.36849213e-04,
        -4.83989716e-05,  7.36474991e-04,  1.46842003e-03,
         2.

In [58]:
is_gt_available = depth_gt > depth_thre
is_gt_available[600:610, 700:710]

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [59]:
len(is_gt_available)

1200

In [60]:
np.sum(is_gt_available)

1884449

In [61]:
is_depth_close = np.logical_and(np.abs(difference) < difference_threshold,
                                is_gt_available)
np.sum(is_depth_close)

546397

In [62]:
mask = is_depth_close.astype(np.float32)
mask[600:610, 700:710]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [63]:
np.sum(mask)

546397.0

In [64]:
mean_difference = np.sum(difference * mask) / np.sum(mask)
mean_difference

1.0053648302954721e-08

In [65]:
var_difference = np.sum(np.square((difference - mean_difference)*mask)) / np.sum(mask)
var_difference

4.488869081940359e-06

In [66]:
std_difference = np.sqrt(var_difference)
std_difference

0.002118695136620736

In [67]:
difference = (difference - mean_difference) / std_difference
difference[600:610, 700:710]

array([[-1.12525705, -1.04845474, -0.86204737, -0.57981999, -0.22681069,
         0.16485296,  0.56653185,  0.95797044,  1.32060113,  1.63028604],
       [-0.97131484, -0.90931033, -0.73775704, -0.4713965 , -0.13509804,
         0.2403049 ,  0.62802997,  1.0079904 ,  1.36235007,  1.66759002],
       [-1.00023527, -0.94937132, -0.79171559, -0.54352878, -0.22816106,
         0.12749272,  0.50002612,  0.86862094,  1.21307789,  1.51044068],
       [-1.21871392, -1.1713947 , -1.018409  , -0.77787429, -0.47280314,
        -0.12733341,  0.23839188,  0.60299185,  0.94373529,  1.23637178],
       [-1.52063421, -1.4684199 , -1.30823222, -1.05976409, -0.74720963,
        -0.39498805, -0.02284851,  0.34760307,  0.6930728 ,  0.98739726],
       [-1.7512662 , -1.68768627, -1.51247573, -1.2457776 , -0.91184228,
        -0.53773344, -0.14713884,  0.23732283,  0.59308914,  0.8929276 ],
       [-1.79757265, -1.721333  , -1.5320561 , -1.24740929, -0.88944864,
        -0.4883324 , -0.07466897,  0.32504063

In [35]:
difference *= mask
difference[600:610, 700:710]

array([[-6.22319173e-01,  6.40848383e-02,  6.49145990e-01,
         9.91011019e-01,  1.03446277e+00,  8.02630954e-01,
         4.19854428e-01,  6.07423957e-02, -1.31381205e-01,
        -9.95611512e-02],
       [-8.77681787e-01, -2.41147019e-01,  3.60091555e-01,
         7.70409807e-01,  9.08385838e-01,  7.72281575e-01,
         4.61835507e-01,  1.38019668e-01, -5.35691411e-02,
        -3.96645799e-02],
       [-1.06579446e+00, -5.09612009e-01,  8.22677260e-02,
         5.42054129e-01,  7.63591225e-01,  7.20139471e-01,
         4.85098908e-01,  2.00456496e-01,  9.40247744e-03,
         1.51431292e-03],
       [-1.17007867e+00, -7.16442357e-01, -1.56248978e-01,
         3.34555293e-01,  6.24278217e-01,  6.61178783e-01,
         4.90580513e-01,  2.35351597e-01,  3.60083205e-02,
        -2.23757234e-04],
       [-1.17756574e+00, -8.42118198e-01, -3.36473482e-01,
         1.61015674e-01,  4.98468678e-01,  5.98340863e-01,
         4.77745534e-01,  2.39228830e-01,  2.21037593e-02,
        -4.

In [47]:
difference *= std_difference
difference[600:610, 700:710]

array([[-1.10976067e-03,  1.14280318e-04,  1.15760002e-03,
         1.76723633e-03,  1.84472236e-03,  1.43130455e-03,
         7.48712157e-04,  1.08319853e-04, -2.34287645e-04,
        -1.77544023e-04],
       [-1.56514015e-03, -4.30029298e-04,  6.42139052e-04,
         1.37384567e-03,  1.61989364e-03,  1.37718353e-03,
         8.23575591e-04,  2.46125792e-04, -9.55280317e-05,
        -7.07324995e-05],
       [-1.90059509e-03, -9.08773805e-04,  1.46705245e-04,
         9.66626738e-04,  1.36168632e-03,  1.28420029e-03,
         8.65060423e-04,  3.57467269e-04,  1.67671190e-05,
         2.70042284e-06],
       [-2.08656159e-03, -1.27760735e-03, -2.78633500e-04,
         5.96601103e-04,  1.11325416e-03,  1.17905769e-03,
         8.74835585e-04,  4.19694518e-04,  6.42124163e-05,
        -3.99018684e-07],
       [-2.09991303e-03, -1.50172081e-03, -6.00021745e-04,
         2.87133788e-04,  8.88902281e-04,  1.06700096e-03,
         8.51947402e-04,  4.26608656e-04,  3.94168840e-05,
        -8.

In [48]:
depth_difference = difference + 1
depth_difference *= mask
depth_difference[600:610, 700:710]

array([[0.99889024, 1.00011428, 1.0011576 , 1.00176724, 1.00184472,
        1.0014313 , 1.00074871, 1.00010832, 0.99976571, 0.99982246],
       [0.99843486, 0.99956997, 1.00064214, 1.00137385, 1.00161989,
        1.00137718, 1.00082358, 1.00024613, 0.99990447, 0.99992927],
       [0.9980994 , 0.99909123, 1.00014671, 1.00096663, 1.00136169,
        1.0012842 , 1.00086506, 1.00035747, 1.00001677, 1.0000027 ],
       [0.99791344, 0.99872239, 0.99972137, 1.0005966 , 1.00111325,
        1.00117906, 1.00087484, 1.00041969, 1.00006421, 0.9999996 ],
       [0.99790009, 0.99849828, 0.99939998, 1.00028713, 1.0008889 ,
        1.001067  , 1.00085195, 1.00042661, 1.00003942, 0.99991353],
       [0.99804934, 0.99841722, 0.99918063, 1.00003012, 1.00067504,
        1.00093682, 1.0007964 , 1.00039585, 0.99997457, 0.99977978],
       [0.99831803, 0.99844964, 0.9990414 , 0.99980767, 1.0004557 ,
        1.00077851, 1.00071057, 1.00034459, 0.9998978 , 0.99962886],
       [0.99865707, 0.99856051, 0.9989653

In [49]:
cam_params = {
    'focal_length': 0.037009,
    'pix_x': 1.25e-05,
    'pix_y': 1.2381443057539635e-05,
    'center_x': 790.902,
    'center_y': 600.635
}

In [50]:
xyz = depth_tools.convert_depth_to_coords(depth_difference, cam_params)
depth_tools.dump_ply('difference{:03d}.ply'.format(data_idx), xyz.reshape(-1, 3).tolist())

In [51]:
np.mean(depth_difference)

0.2636317708333333